config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios
  #resources :comentarios
  #get 'articulos/new'
  get 'articulos/index'

  #con esto creamos todas las rutas del recurso articulo directamente
  resources :articulos do
    resources :comentarios
  end

  get 'estaticas/contacto'
  get 'estaticas/nosotros'
  
  get 'home/index'
  #aqui le estamos indicando que la raiz es el controler home y la vista index
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/articulo.rb
class Articulo < ActiveRecord::Base
  belongs_to :autor
  has_many :comentarios
  validates :titulo, presence: {:message => "no puede estar vacío"}
  validates :contenido, presence: {:message => "es demasiado corto, debe de tener mínimo de 50 carácteres"}, length: {minimum: 50}
end

app/models/comentario.rb
class Comentario < ApplicationRecord
  belongs_to :articulo
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
  
  def index
    @articulos=Articulo.all.order("created_at DESC")
  end
  
  def new
    @articulo = Articulo.new
  end

  def create
    @articulo = Articulo.new (articulo_params)
    if @articulo.save
      redirect_to @articulo
    else
      render 'new'
    end
  end

  def edit
    @articulo=Articulo.find(params[:id])
  end

  def update
    @articulo=Articulo.find(params[:id])
    if @articulo.update.find(articulo_params)
      flash[:notice] = "El artículo se ha modificado correctamente"
      redict_to @articulo
    else
      render 'edit'
    end
  end

  def show
    @articulo=Articulo.find(params[:id])
  end

  def destroy
    @articulo=Articulo.find(params[:id])
    @articulo.destroy
    redirect_to articulos_path, :notice=>"Artículo eliminado correctamente"
  end

    private
  def articulo_params
    params.require(:articulo).permit(:titulo, :contenido)
  end 
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_comentario, only: %i[ show edit update destroy ]

  # GET /comentarios or /comentarios.json
  def index
    @comentarios = Comentario.all
  end

  # GET /comentarios/1 or /comentarios/1.json
  def show
  end

  # GET /comentarios/new
  def new
    @comentario = Comentario.new
  end

  # GET /comentarios/1/edit
  def edit
  end

  # POST /comentarios or /comentarios.json
  def create
    @comentario = Comentario.new(comentario_params)
    #esto permite soportar diferentes tipos de formato
    respond_to do |format|
      if @comentario.save
        format.html { redirect_to @comentario, notice: "Comentario was successfully created." }
        format.json { render :show, status: :created, location: @comentario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comentarios/1 or /comentarios/1.json
  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to @comentario, notice: "Comentario was successfully updated." }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1 or /comentarios/1.json
  def destroy
    @comentario.destroy
    respond_to do |format|
      format.html { redirect_to comentarios_url, notice: "Comentario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comentario_params
      params.require(:comentario).permit(:nombre, :texto, :articulo_id)
    end
end

app/controllers/estaticas_controller.rb
class EstaticasController < ApplicationController
  def contacto
    @id = params[:id]
    @pag = params[:pagina]
  end

  def nosotros
    @mensaje = "Bienvenidos a tod@s de nuevo a mi blog!"
    @usuarios = ['Miryam', 'Sergio', 'Oliver', "Luca"]
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articulos_helper.rb
module ArticulosHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/estaticas_helper.rb
module EstaticasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articulos/_form.html.erb
<%= form_for @articulo do |f| %>
  <% if @articulo.errors.any? %>
    <div id= "errors">
        <h2><% pluralize(@articulo.errors.count, "error") %> Se han producido los siguientes errores:</h2>
        <ul>
            <% @articulo.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
    <% end %>

    <%= f.label :titulo %>
    <br>
    <%= f.text_field :titulo %>
    <br>

    <%= f.label :contenido %>
    <br>
    <%= f.text_area :contenido %>
    <br>
    <%= f.submit "Crear Artículo" %>

<% end %>

app/views/articulos/edit.html.erb
<h1>Articulos</h1>


<%# aqui ponemos el parcial %>
<%= render 'form' %>

app/views/articulos/index.html.erb
<h1>Articulos</h1>

<% @articulos.each do |art|%>
    <h2><%= link_to art.titulo, art%></h2>
    <p><%= art.created_at.strftime("%d-$m-%Y")%></p>
    <p><%= art.contenido.truncate_words(30)%></p>
<% end %>

app/views/articulos/new.html.erb
<h1>Escribe tu artículo</h1>

<%# aqui tenemos el parcial form %>
<%= render 'form' %>

app/views/articulos/show.html.erb
<h1><%=@articlo.titulo %></h1>

<p>Creado el <%=@articulo.created_at.strftime ("%d-%m-%Y")%></p>

<p><%=@articulo.contenido%></p>

<%= link_to "Editar", editar_articulo_path(@articulo) %>
<%= link_to "Elininar", @articulo, :method => :delete, data: {confirm: "¿Seguro que quiere eliminar el artículo?"}%>

app/views/comentarios/_form.html.erb
<%= form_with(model: comentario) do |form| %>
  <% if comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
        <% comentario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_area :nombre %>
  </div>

  <div class="field">
    <%= form.label :texto %>
    <%= form.text_field :texto %>
  </div>

  <div class="field">
    <%= form.label :articulo_id %>
    <%= form.text_field :articulo_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comentarios/edit.html.erb
<h1>Editing Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

app/views/comentarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comentarios</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Texto</th>
      <th>Articulo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.nombre %></td>
        <td><%= comentario.texto %></td>
        <td><%= comentario.articulo_id %></td>
        <td><%= link_to 'Show', comentario %></td>
        <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
        <td><%= link_to 'Destroy', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comentario', new_comentario_path %>

app/views/comentarios/new.html.erb
<h1>New Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Back', comentarios_path %>

app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @comentario.nombre %>
</p>

<p>
  <strong>Texto:</strong>
  <%= @comentario.texto %>
</p>

<p>
  <strong>Articulo:</strong>
  <%= @comentario.articulo_id %>
</p>

<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>

app/views/estaticas/contacto.html.erb
<%= provide(:titulo, "Contacto")%>
<p>Aquí puedes contactar con nosotros</p>

<% #params.inspect  %>

<br>

<p>ID: <%= @id %></p>
<p>PAG: <%= @pagina %></p>

<%= content_for(:saludo, "Hola")  %>
<%= yield :saludo %>

app/views/estaticas/nosotros.html.erb
<%= provide(:titulo, "Nosotros")%>
<p>Aquí podrás saber un poco sobre nosotros</p>

<%= @mensaje %>
<br>

<ul>
    <%= @usuarios.each do |i| %>
        <%= "<li> #{i} </li>".html_safe %>
    <% end %>
</ul>


<%= link_to 'Home', root_path %>
<%= link_to 'Contacto', estaticas_contacto_path %>

<br>

app/views/home/index.html.erb
<%= provide(:titulo, "Mi Blog")%>
<p>Bienvenidos a mi Blog!</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:titulo)%></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
  <%# aqui ponemos el parcial %>
    <%= render 'shared/header'%>
    <ul>
      <%= flash.each do |key, value| %>
      <li><%= value %></li>
      <% end %>
    </ul>

    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
  
  <%# yield muestra el contenido de cada vista en concreto %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/shared/_header.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'Contacto', estaticas_contacto_path %>
<%= link_to 'Nosotros', estaticas_nosotros_path %>